name: Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  test-linux64:
    runs-on: ubuntu-latest

    steps:
    - name: Run test script on Linux.
      run: |
        git clone https://github.com/Embroidermodder/embroidermodder
        cd embroidermodder
        ./build.sh --get-dependencies
        ./build.sh --build
    - name: Upload artifact to act as the Linux Nightly
      uses: actions/upload-artifact@v2
      with:
        name: embroidermodder_2_alpha_linux
        path: build
  test-macOS:
    runs-on: macOS-latest
    
    steps:
    - name: Run test script on macOS.
      run: |
        git clone https://github.com/Embroidermodder/embroidermodder
        cd embroidermodder
        ./build.sh --get-dependencies
        ./build.sh --build
    - name: Upload artifact to act as the Mac OS Nightly
      uses: actions/upload-artifact@v2
      with:
        name: embroidermodder_2_alpha_macos
        path: build
  test-windows:
    runs-on: windows-latest

    steps:
    - name: Run test script on Windows.
      run: |
        git clone https://github.com/Embroidermodder/embroidermodder
        cd embroidermodder
        .\build.bat
    - name: Upload artifact to act as the Windows
      uses: actions/upload-artifact@v2
      with:
        name: embroidermodder_2_alpha_windows
        path: build
