name: Test Suite

on: [push]

jobs:
  nightly:
    name: Tests and produces nightly assets.
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run test script.
      run: |
        git clone https://github.com/Embroidermodder/embroidermodder
        cd embroidermodder
        ./build.sh --get-dependencies
        ./build.sh --build
      shell: bash
    - name: Upload artifact to act as the ${{ matrix.os }} Nightly
      uses: actions/upload-artifact@v2
      with:
        name: embroidermodder_2_alpha_${{ matrix.os }}
        path: ${{ github.workspace }}/embroidermodder/build
