name: Test Suite

on:
  push:
    branches: [ master ]

jobs:
  nightly:
    name: Tests and produces nightly assets.
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run test script.
      run: |
        git clone https://github.com/Embroidermodder/embroidermodder
        cd embroidermodder
        ./build.sh --get-dependencies
        ./build.sh --build
      shell: bash
    - name: Upload artifact to act as the ${{ matrix.os }} Nightly
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: embroidermodder_2_alpha_${{ matrix.os }}
        path: /home/runner/work/Embroidermodder/Embroidermodder/embroidermodder/build
    - name: Upload artifact to act as the Mac OS Nightly
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-artifact@v2
      with:
        name: embroidermodder_2_alpha_macos
        path: /Users/runner/work/Embroidermodder/Embroidermodder/embroidermodder/build
    - name: Upload artifact to act as the Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: embroidermodder_2_alpha_windows
        path: D:\a\Embroidermodder\Embroidermodder\embroidermodder\build
